namespace SDTechnicalAssessment.Application.DTOs
{
    // DTO used when creating a new product.
    // Id and audit fields are generated by the server.
    public class CreateProductDto
    {
        // Product name entered by the client.
        public string ProductName { get; set; } = string.Empty;

        // Person creating the product.
        public string CreatedBy { get; set; } = string.Empty;
    }
}